name: u3_tarea2

on:
push:
    branches:
    - main

jobs:
    build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repository
    uses: actions/checkout@v2

    - name: Set up Go environment
    uses: actions/setup-go@v2
        with: 
        go-version: '1.16'

    - name: Install Hugo
        run: |
        wget https://github.com/gohugoio/hugo/releases/download/v.0.81.0/hugo_extended_0.81.0_Linux_64bit.tar.gz
        tar -xzf hugo_extended_0.81.0_Linux_64bit.tar.gz
        sudo mv hugo/usr/local/bin/

    - name: Run linting on Markdown files
        run: make lint

    -name: Build and package application
        run: |
        make build
        make package

    -name: Archive artifact
        if: success()
        uses: actions/upload-artifact@v2
